all:
	javac -d . Payable.java
	javac -d . Employee.java
	javac -d . CommissionEmployee.java
	javac -d . BasePlusCommissionEmployee.java
	javac -d . HourlyEmployee.java
	javac -d . SalariedEmployee.java
	javac -d . Invoice.java
	javac -d . PayableInterfaceTest.java
	javac -d . PayrollSystemTest.java
run:
	java exe10_16.PayrollSystemTest
	java exe10_16.PayableInterfaceTest
delete:
	rm -r exe10_16
