all:Card DeckOfCards DeckOfCardsTest TwoHandsDeal FisherYatesShuffle FisherYatesShuffleTest
Card:Card.java
	javac -d . Card.java
DeckOfCards:DeckOfCards.java
	javac -d . DeckOfCards.java
DeckOfCardsTest:DeckOfCardsTest.java
	javac -d . DeckOfCardsTest.java
TwoHandsDeal:TwoHandsDeal.java
	javac -d . TwoHandsDeal.java
FisherYatesShuffle:FisherYatesShuffle.java
	javac -d . FisherYatesShuffle.java
FisherYatesShuffleTest:FisherYatesShuffleTest.java
	javac -d . FisherYatesShuffleTest.java



run:TwoHandsDeal FisherYatesShuffleTest
	echo '-----------7.31--------------'
	java C7.TwoHandsDeal
	echo '-----------7.31--------------'
	echo '-----------7.35--------------'
	java C7.FisherYatesShuffleTest
	echo '-----------7.35--------------'

	
