all:
	javac -d . CarbonFootprint.java
	javac -d . Building.java
	javac -d . Bicycle.java
	javac -d . Car.java
	javac -d . CarbonFootprintTest.java
run:
	java exe10_17.CarbonFootprintTest
delete:
	rm -r exe10_17
